export default {
  COLOR_BACKGROUND: "#292929",
  COLOR_CALCULATOR: "#323232",
  COLOR_BUTTON: "#404040",
  COLOR_BUTTON_PLUS: "#5A5D5F",
  COLOR_BUTTON_MINUS: "#903C3C",
  COLOR_TEXT: "#FBF3F3",
  COLOR_TEXT_NEGATIVE: "#FF6A6A",
  COLOR_DISPLAY: "#1E1E1E",
  COLOR_DISPLAY_TEXT: "#00ECF8",
  FONT_XL: 32,
  FONT_LG: 24,
  FONT_MD: 18,
  FONT_SM: 16,
  SPACE_LG: 24,
  SPACE_MD: 16,
  SPACE_SM: 8,
  SPACE_XS: 4,
  BORDER_RADIUS_MD: 16,
  BORDER_RADIUS_SM: 8,
  SHADOW_MD: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  SHADOW_SM: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
};
